quarkus:
  http:
    # see README: S3 Event Notifications
    host: 0.0.0.0
  rest-client:
    fake-service:
      uri: http://localhost:8081/fake
  compose:
    devservices:
      env-variables:
        APP_PORT: "8081"
s3:
  uri: http://localhost:${s3.port}
  event-queue: "arn:minio:sqs::_:webhook"
