quarkus:
  compose:
    devservices:
      enabled: true
      files: src/dev/compose.yaml
  swagger-ui:
    always-include: true
    deep-linking: true
    display-request-duration: true
    path: /rest-ui
    theme: muted
    try-it-out-enabled: true
